/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Stratege.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'Stratege.view.MainViewViewModel',
        'Stratege.view.decision.Form',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            split: false,
            height: 150,
            itemId: 'headerPanel',
            title: 'Header'
        },
        {
            xtype: 'panel',
            region: 'south',
            split: false,
            height: 150,
            itemId: 'footerPanel',
            title: 'Footer'
        },
        {
            xtype: 'decisionform',
            region: 'center'
        }
    ]

});