/*
 * File: app/view/decision/FormViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Stratege.view.decision.FormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.decisionform',
	
	uses: ['Ext.JSON', 'Ext.data.JsonP'],

    onFormSubmit: function(button, e, eOpts) {
        var form = this.getView().getForm();
        var values = form.getValues();
		var decision;
		
		// form is valid, send the data
		if (!form.isValid()) {
			Ext.Msg.alert('Erreur !', 'invalid values');
			return false;
		}
		
		values.seminarId = 1;
		values.groupId = 1;
		values.period = 1;
		values.d_CID = 1;
		values.d_CompanyName = "Masters";
		
		decision = this._extractDecision(values);
		
		Ext.Msg.wait('Connection', 'Envoi...');
		
		Ext.Ajax.request({
            url: 'http://localhost:1337/decisions',
            method: 'POST',
			jsonSubmit: true,
			disableCaching: true,
			
			jsonData: decision,
			
            headers: { 
				'Content-Type': 'application/json;charset=utf-8',
				'Access-Control-Allow-Origin': 'http://localhost:1337'
			},
			
			waitTitle: 'Connection', 
          	waitMsg: 'Envoi...',
			
			success: function(response, opts) {
                var result = Ext.decode(response.responseText);
				
				Ext.Msg.alert('Opération Réussie!', result.msg);
            },
			
			failure: function(response, opts) {
				var status = response.status;
				
				Ext.Msg.alert('Echec de Connection !',  status);			   
			}
		});
		
		/*
		form.submit({
            url: 'http://localhost:1337/decisions',
            method: 'POST',
			jsonSubmit: true,
			
            headers: { 
				'Content-Type': 'application/json;charset=utf-8',
				'Access-Control-Allow-Origin': 'http://localhost:1337'
			},
						
			waitTitle: 'Connection', 
          	waitMsg: 'Envoi...',
		  
            success: function (form, action) {
                var result = action.result;
				
				Ext.Msg.alert('Opération Réussie!', 'Votre Décision a été bien enregistrée !');
            },
			
			failure: function(form, action) {
				switch (action.failureType) {
					case Ext.form.action.Action.CLIENT_INVALID:
						Ext.Msg.alert('Echec de Connection !', 'Form fields may not be submitted with invalid values');
						break;
					case Ext.form.action.Action.CONNECT_FAILURE:
						Ext.Msg.alert('Echec de Connection !',  'Ajax communication failed');
						break;
					case Ext.form.action.Action.SERVER_INVALID:
						Ext.Msg.alert('Echec de Connection !',  action.result.msg);
			   }
			}
        });*/
		
    },
	
	_extractDecision: function (v) {
		var decision = {
			seminarId: v.seminarId,
			groupId: v.groupId,
			period: v.period,
			d_CID: v.CID,
			d_CompanyName: v.CompanyName,
	
			markets: [
				{
					corporateComBudget: v.m1_corporate,
	
					agents: [{
						appointedNb: v.m1_agents_appointedNb,
						commissionRate: v.m1_agents_commissionRate,
						support: v.m1_agents_support
					}],
	
					subMarkets: [{
						advertisingBudget: v.m1_p1_advertising,
						price: v.m1_p1_price,
						deliveredQ: v.m1_p1_deliveredQ
					}, {
							advertisingBudget: v.m1_p2_advertising,
							price: v.m1_p2_price,
							deliveredQ: v.m1_p2_deliveredQ
						}, {
							advertisingBudget: v.m1_p3_advertising,
							price: v.m1_p3_price,
							deliveredQ: v.m1_p3_deliveredQ
						}]
				}, {
					corporateComBudget: v.m2_corporate,
	
					agents: [{
						appointedNb: v.m2_agents_appointedNb,
						commissionRate: v.m2_agents_commissionRate,
						support: v.m2_agents_support
					}],
	
					subMarkets: [{
						advertisingBudget: v.m2_p1_advertising,
						price: v.m2_p1_price,
						deliveredQ: v.m2_p1_deliveredQ
					}, {
							advertisingBudget: v.m2_p2_advertising,
							price: v.m2_p2_price,
							deliveredQ: v.m2_p2_deliveredQ
						}, {
							advertisingBudget: v.m2_p3_advertising,
							price: v.m2_p3_price,
							deliveredQ: v.m2_p3_deliveredQ
						}]
				}, {
					corporateComBudget: v.m3_corporate,
	
					agents: [{
						appointedNb: 0,
						commissionRate: v.m3_agents_commissionRate,
						support: v.m3_agents_support
					}],
	
					subMarkets: [{
						advertisingBudget: v.m3_p1_advertising,
						price: v.m3_p1_price,
						deliveredQ: v.m3_p1_deliveredQ
					}, {
							advertisingBudget: v.m3_p2_advertising,
							price: v.m3_p2_price,
							deliveredQ: v.m3_p2_deliveredQ
						}, {
							advertisingBudget: v.m3_p3_advertising,
							price: v.m3_p3_price,
							deliveredQ: v.m3_p3_deliveredQ
						}]
				}
	
			],
	
			products: [
				{
					manufacturingTime: [0, v.p1_assemblyTime],
					improvementsTakeup: v.p1_takeupImprovements,
					developmentBudget: v.p1_devBudget,
					premiumMaterialPropertion: v.p1_premiumMaterialProp,
					componentsOrdered: v.p1_subcontractQ
				}, {
					manufacturingTime: [0, v.p2_assemblyTime],
					improvementsTakeup: v.p2_takeupImprovements,
					developmentBudget: v.p2_devBudget,
					premiumMaterialPropertion: v.p2_premiumMaterialProp,
					componentsOrdered: v.p2_subcontractQ
				}, {
					manufacturingTime: [0, v.p3_assemblyTime],
					improvementsTakeup: v.p3_takeupImprovements,
					developmentBudget: v.p3_devBudget,
					premiumMaterialPropertion: v.p3_premiumMaterialProp,
					componentsOrdered: v.p3_subcontractQ
				}
			],
	
			materials: [{
				purchases: [{
					term: 0,
					quantity: v.purchases_spotQ
				}, {
						term: 1,
						quantity: v.purchases_3mthQ
					}, {
						term: 2,
						quantity: v.purchases_6mthQ
					}]
			}],
	
			machines: [{
				maintenanceHours: v.machine_maintenance_hoursNb,
				boughtNb: v.machine_boughtNb,
				soldNb: v.machine_soldNb
			}],
	
			shiftLevel: v.shift_level,
	
			factories: [{
				extension: v.factory_extension
			}],
	
			websitePortsNb: v.website_portsNb,
			websiteDevBudget: v.website_devBudget,
	
	
			insurancePlan: v.insurance_plan,
			sharesVariation: v.shares_variation,
			termLoans: v.term_loans,
			termDeposit: v.term_deposit,
			dividend: v.dividend,
	
			orderMarketSharesInfo: v.intelligence_marketShares_order,
			orderCorporateActivityInfo: v.intelligence_corporateInfo_order,
	
			staffTrainingDays: v.management_trainning,
			managementBudget: v.management_budget,
	
			workers: [{
				hourlyWageRate: v.assemblyWorkers_wageRate,
				hire: 0,
				trainedNb: 0
			}, {
					hourlyWageRate: v.assemblyWorkers_wageRate,
					hire: v.assemblyWorkers_hire,
					trainedNb: v.assemblyWorkers_trainedNb
				}]
	
	
	
		};
	
		return decision;
	}

});
