/*
 * File: app/view/decision/Form.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Stratege.view.decision.Form', {
    extend: 'Ext.form.Panel',
    alias: 'widget.decisionform',

    requires: [
        'Stratege.view.decision.FormViewModel',
        'Stratege.view.decision.FormViewController',
        'Ext.form.FieldSet',
        'Ext.form.Label',
        'Ext.form.field.Spinner',
        'Ext.form.field.Checkbox',
        'Ext.form.FieldContainer',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],
	
	controller: 'decisionform',
    viewModel: {
        type: 'decisionform'
    },
	
    itemId: 'rightPanel',
    scrollable: 'true',
    title: 'Right',

    layout: {
        type: 'vbox',
        align: 'stretchmax',
        pack: 'center'
    },
    items: [
        {
            xtype: 'fieldset',
            title: 'Promotion',
            layout: {
                type: 'table',
                columns: 5
            },
            items: [
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Marché'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Produit 1'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Produit 2'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Produit 3'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Corporate'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'E.U'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p1_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p2_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p3_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_corporate'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Nafta'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p1_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p2_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p3_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_corporate'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 150,
                    text: 'Internet'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p1_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p2_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p3_advertising'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_corporate'
                }
            ]
        },
        {
            xtype: 'fieldset',
            title: 'Prix ( Dh)',
            layout: {
                type: 'table',
                columns: 5
            },
            items: [
                
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'E.U'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p1_price'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p2_price'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p3_price'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Nafta'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p1_price'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p2_price'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p3_price'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 150,
                    text: 'Internet'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p1_price'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p2_price'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p3_price'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 168,
            title: 'Livraisons',
            layout: {
                type: 'table',
                columns: 6
            },
            items: [
                
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: 'E.U'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p1_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p2_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_p3_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: 'Nafta'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p1_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p2_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_p3_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    minWidth: 500,
                    padding: '5 20',
                    width: 70,
                    text: 'Internet'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p1_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p2_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_p3_deliveredQ'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 168,
            title: 'Agents et Distributeurs',
            layout: {
                type: 'table',
                columns: 6
            },
            items: [
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: ''
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Nombre voulu'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Soutien Financier '
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200,
                    text: 'Commission (%)'
                },
                {
                    xtype: 'label',
                    padding: '5 20',
                    width: 200
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: 'E.U'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_agents_appointedNb'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_agents_support'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm1_agents_commissionRate'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: 'Nafta'
                },
                                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_agents_appointedNb'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_agents_support'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm2_agents_commissionRate'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    minWidth: 500,
                    padding: '5 20',
                    width: 70,
                    text: 'Internet'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: ''
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_agents_support'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'm3_agents_commissionRate'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 168,
            title: 'Qualité',
            layout: {
                type: 'table',
                columns: 6
            },
            items: [
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: 'Perfectionnements adoptés'
                },
                {
                    xtype: 'checkboxfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p1_takeupImprovements',
                    boxLabelAlign: 'before'
                },
                {
                    xtype: 'checkboxfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p2_takeupImprovements'
                },
                {
                    xtype: 'checkboxfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p3_takeupImprovements'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: 'Dépenses R & D'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p1_devBudget'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p2_devBudget'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p3_devBudget'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 150,
                    text: 'Temps montage (minutes)'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p1_assemblyTime'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p2_assemblyTime'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p3_assemblyTime'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 150,
                    text: 'Matières premières haute qualité en %'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p1_premiumMaterialProp'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p2_premiumMaterialProp'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p3_premiumMaterialProp'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 176,
            title: 'Opérations',
            layout: {
                type: 'table',
                columns: 6
            },
            items: [
                {
                    xtype: 'label',
                    colspan: 2,
                    padding: '5 20',
                    width: 200,
                    text: 'Composants sous-traités'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p1_subcontractQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p2_subcontractQ'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'p3_subcontractQ'
                },
                {
                    xtype: 'numberfield',
                    disabled: true,
                    fieldLabel: 'Label',
                    hideLabel: true
                },
                {
                    xtype: 'fieldcontainer',
                    colspan: 6,
                    rowspan: 1,
                    height: 120,
                    fieldLabel: 'Achats: Matières Premières',
                    labelWidth: 200,
                    items: [
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Spot',
							name: 'purchases_spotQ'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '3 mois',
							name: 'purchases_3mthQ'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '6 mois',
							name: 'purchases_6mthQ'
                        }
                    ]
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Heures maintenance / machine',
                    labelWidth: 200,
					name: 'machine_maintenance_hoursNb'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Nombre rotation équipes (1-3)',
                    labelWidth: 200,
					name: 'shift_level'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Nombre total Ports opérationnels',
                    labelWidth: 200,
					name: 'website_portsNb'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Développement site internet',
                    labelWidth: 200,
					name: 'website_devBudget'
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 168,
            title: 'Personnel',
            layout: {
                type: 'table',
                columns: 6
            },
            items: [
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Ouvriers qualifiés recrut (+) / licenc (-)',
                    labelWidth: 200,
					name: 'assemblyWorkers_hire'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Ouvriers qualifiés formés',
                    labelWidth: 200,
					name: 'assemblyWorkers_trainedNb'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Budget Gestion (\' dh)',
                    labelWidth: 200,
					name: 'management_budget'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Formation (en jours)',
                    labelWidth: 200,
					name: 'management_trainning'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Salaire horaire Ouvriers qualifiés (centimes)',
                    labelWidth: 200,
					name: 'assemblyWorkers_wageRate'
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 168,
            title: 'Finances',
            layout: {
                type: 'table',
                columns: 6
            },
            items: [
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Actions émises ou revendues',
                    labelWidth: 200,
					name: 'shares_variation'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Dividende (%)',
                    labelWidth: 200,
					name: 'dividend'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Emprunts Moyen Terme ',
                    labelWidth: 200,
					name: 'term_loans'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Compte Courant  (+/- dh)',
                    labelWidth: 200,
					name: 'term_deposit'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Achat machines',
                    labelWidth: 200,
					name: 'machine_boughtNb'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Vente machines',
                    labelWidth: 200,
					name: 'machine_soldNb'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Agrandissement de l\'usine (m2)',
                    labelWidth: 200,
					name: 'factory_extension'
                },
                {
                    xtype: 'numberfield',
                    colspan: 3,
                    fieldLabel: 'Plan assurance n°(0-4)',
                    labelWidth: 200,
					name: 'insurance_plan'
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 168,
            title: 'Intelligence économique',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'checkboxfield',
                    flex: 1,
                    fieldLabel: 'Parts de Marché',
                    labelWidth: 200,
                    boxLabel: '',
					name: 'intelligence_marketShares_order'
                },
                {
                    xtype: 'checkboxfield',
                    flex: 1,
                    fieldLabel: 'Infos sur autres entreprises',
                    labelWidth: 200,
                    boxLabel: '',
                    boxLabelAlign: 'before',
					name: 'intelligence_corporateInfo_order'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'bottom',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Envoyer',
					
					listeners: {
						click: 'onFormSubmit'	
					}
                }
            ]
        }
    ]

});